// Generated by CoffeeScript 1.5.0

/*
# This file provides simple JSON extensions
*/


(function() {
  var fs, json, jsonlint, parseFile, path, prettify, saveJSON, saveToFile, validate, _;

  path = require('path');

  fs = require('fs');

  _ = require('underscore');

  jsonlint = require('jsonlint');

  json = require('../main');

  parseFile = module.exports.parseFile = function(file, cb) {
    return fs.readFile(file, 'utf-8', function(err, data) {
      if (err) {
        return cb(err);
      } else {
        try {
          return cb(null, json.parse(data));
        } catch (e) {
          return cb(e);
        }
      }
    });
  };

  prettify = module.exports.prettify = function(v, indent) {
    if (indent == null) {
      indent = "\t";
    }
    return json.stringify(v, null, indent);
  };

  saveToFile = module.exports.saveToFile = function(data, file, indent, cb) {
    var fstream, _ref,
      _this = this;
    if (_.isFunction(indent)) {
      _ref = [indent, null], cb = _ref[0], indent = _ref[1];
    }
    cb = _.isFunction(cb) ? _.once(cb) : function() {};
    fstream = fs.createWriteStream(file, {
      flags: "w"
    });
    fstream.on("error", function(err) {
      return cb(err);
    });
    fstream.on("close", function() {
      return cb();
    });
    return fstream.end(json.stringify(data, null, indent));
  };

  saveJSON = module.exports.saveJSON = saveToFile;

  validate = module.exports.validate = function(rawjson) {
    try {
      json.parse(rawjson);
      return null;
    } catch (e) {
      return e;
    }
  };

}).call(this);
