// Generated by CoffeeScript 1.5.0

/*
# This file provides simple JSON extensions
*/


(function() {
  var fs, json, parseFile, path, prettify, saveJSON, _;

  path = require('path');

  fs = require('fs');

  _ = require('underscore');

  json = require('../main');

  parseFile = module.exports.parseFile = function(file, cb) {
    return fs.readFile(file, 'utf-8', function(err, data) {
      if (err) {
        return cb(err);
      } else {
        return cb(null, json.parse(data));
      }
    });
  };

  prettify = module.exports.prettify = function(v, indent) {
    if (indent == null) {
      indent = "\t";
    }
    return json.stringify(v, null, indent);
  };

  saveJSON = module.exports.saveJSON = function(data, file, indent, cb) {
    var fstream, _ref,
      _this = this;
    if (_.isFunction(indent)) {
      _ref = [indent, null], cb = _ref[0], indent = _ref[1];
    }
    cb = _.isFunction(cb) ? _.once(cb) : function() {};
    fstream = fs.createWriteStream(file, {
      flags: "w"
    });
    fstream.on("error", function(err) {
      return cb(err);
    });
    fstream.on("close", function() {
      return cb();
    });
    return fstream.end(json.stringify(data, null, indent));
  };

}).call(this);
